name: Release

on: push

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      actions: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
          stable: true

      - name: å®‰è£…sdk
        run: |
          git clone --recursive https://github.com/Ai-Thinker-Open/Ai-Thinker-WB2.git
      
      - name: èµ‹äºˆæƒé™å¹¶æ‰§è¡Œ
        run: |
          ls Ai-Thinker-WB2/toolchain/riscv/Linux
          rm -rf Ai-Thinker-WB2/toolchain/riscv/Linux/chmod755.sh
          mv chmod755.sh Ai-Thinker-WB2/toolchain/riscv/Linux/.
          bash Ai-Thinker-WB2/toolchain/riscv/Linux/chmod755.sh         

      - name: ç¼–è¯‘æµ‹è¯•
        run: |
          make -j32
          echo "ç¼–è¯‘å®Œæˆ" 

      - name: åˆ é™¤æ‰€æœ‰ç©ºæ–‡ä»¶ï¼Œé¿å… GitHub æŠ¥é”™
        run: find build_out/ -type f -size 0 -delete

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: latest
          name: "Latest Firmware"
          body: "ğŸš€ è¿™æ˜¯æœ€æ–°çš„å›ºä»¶å‘å¸ƒï¼Œæ¯æ¬¡ push éƒ½ä¼šæ›´æ–°ï¼"
          draft: false
          prerelease: false
          files: |
            build_out/*.bin
            build_out/*.elf
